import React from "react";
import Head from "next/head";

function about() {
  return (
    <div>
      <Head>
        <title>About Page</title>
        <meta
          name="description about page"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>ABOUT PAGE</p>{" "}
    </div>
  );
}

export default about;
