import Head from "next/head";
import ArticelList from "./Components/ArticelList";
export default function Home({ articles }) {
  console.log(articles, "--->API");
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>LEARN NEXT JS</p>

      <div>
        <ArticelList articles={articles} />
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  const resp = await fetch(`https://jsonplaceholder.typicode.com/posts`);

  const articles = await resp.json();

  return {
    props: { articles },
  };
};
